apiVersion: v1
kind: Service
metadata:
  name: acme-frontend-service
  namespace: acme
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      protocol: "TCP"
      targetPort: 80
  type: LoadBalancer
